import XCTest
@testable import SwiftySheets

final class ColumnDSLTests: XCTestCase {
    
    func testColumnAutocomplete() {
        // These static properties are generated by the @GenerateColumns macro
        XCTAssertEqual(Column.A.stringValue, "A")
        XCTAssertEqual(Column.Z.stringValue, "Z")
        XCTAssertEqual(Column.AA.stringValue, "AA")
        XCTAssertEqual(Column.AZ.stringValue, "AZ")
        XCTAssertEqual(Column.ZZ.stringValue, "ZZ")
        
        XCTAssertEqual(Column.A.index, 1)
        XCTAssertEqual(Column.ZZ.index, 702)
    }
    
    func testCellBuilder() {
        let cell = Column.A[1]
        XCTAssertEqual(cell.description, "A1")
        
        let cell2 = Column.Z[100]
        XCTAssertEqual(cell2.description, "Z100")
        
        let cell3 = Column.AA[50]
        XCTAssertEqual(cell3.description, "AA50")
    }
    
    func testRangeOperators() {
        // Column...Column -> Full Column Range (A:C)
        let cols = Column.A...Column.C
        XCTAssertEqual(cols.description, "A:C")
        
        // Single Cell...Single Cell -> Rectangular Range (A1:B2)
        let rect = Column.A[1]...Column.B[2]
        XCTAssertEqual(rect.description, "A1:B2")
        
        // Mixed logic checks
        let large = Column.A[1]...Column.ZZ[1000]
        XCTAssertEqual(large.description, "A1:ZZ1000")
    }
    
    func testColumnOrdering() {
        XCTAssertTrue(Column.A < Column.B)
        XCTAssertTrue(Column.A < Column.AA)
        XCTAssertFalse(Column.B < Column.A)
    }
}
